In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [5]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0], b[0,1], b[1,0])

(2, 3)
1 2 4


In [6]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [8]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [9]:
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [11]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [13]:
e = np.random.random((2,2))
print(e)

[[0.88243338 0.94802587]
 [0.84093417 0.38497986]]


In [14]:
print(c*d) #? 곱셈 이렇게 하는거 아닌듯

[[7. 0.]
 [0. 7.]]


In [15]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# 첫번째 행의 처음부터 2 앞까지(0,1), 두번째 행에서
# 1부터 3 앞까지(1,2)의 값들을 떠와 b에 할당.
# 따라서 b 는 다음과 같은 2x2 array:
# [[2 3]
# [6 7]]
b= a[:2, 1:3]
print(a[0, 1])
b[0, 0] = 77
print(a[0, 1])
# Slicing을 한다고 해서 값을 복사해가는 것이 아니므로
# 값의 변화가 동시에 일어남

2
77


In [16]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# 두 번째 행의 값들을 모두 가져오는 두 가지 방법
row_r1 = a[1, :] # 1차원 행렬 (4,)
row_r2 = a[1:2, :] # 2차원 행렬 (1x4) – 기존 차원 유지
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
# 두 번째 열의 값들을 모두 가져오는 두 가지 방법
col_r1 = a[:,1]
col_r2 = a[:,1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [17]:
x = np.array([[1, 2], [3, 4]])
print(x)
print(x.T)# 전치행렬 (Transposed mat.)
v = np.array([1,2,3])
print(v) # prints “[1 2 3]”
print(v.T) # prints “[1 2 3]”

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [29]:
A=np.array([[1, 1],[2, 1]])
x=np.array([[a],[b]])
print(x)
A_inv=np.linalg.inv([[1, 1],[2, 1]])
print(A_inv)
c=np.array([[15],[25]])
x=np.dot(A_inv,c)
print(x)

[[0]
 [0]]
[[-1.  1.]
 [ 2. -1.]]
[[10.]
 [ 5.]]
